version: '3.8'

services:
  web:
    image: upc_bibliotheque
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bibliotheque_web
    command: ["sh", "-c", "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      API_USER_HOST: "http://api:5000/api"
      MYSQL_ROOT_PASSWORD: "Ch16donbosco"
      MYSQL_DATABASE: "bibliotheque"
      MYSQL_USER: "Devcode"
      MYSQL_PASSWORD: "Ch16donbosco"
      DB_HOST: "db"
      DB_PORT: "3306"
      EMAIL_HOST: "smtp.gmail.com"
      EMAIL_PORT: "587"
      EMAIL_USE_TLS: "True"
      EMAIL_HOST_USER: "katumbachrist007@gmail.com"
      EMAIL_HOST_PASSWORD: "acdtmwzcczntclvn"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq/"
      CELERY_RESULT_BACKEND: "django-db"

  db:
    image: mysql:8.0
    container_name: bibliotheque_db
    environment:
      MYSQL_ROOT_PASSWORD: "Ch16donbosco"
      MYSQL_DATABASE: "bibliotheque"
      MYSQL_USER: "Devcode"
      MYSQL_PASSWORD: "Ch16donbosco"
    ports:
      - "3307:3306"
    volumes:
      - upc_bibliotheque_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  # api:
  #   image: api_users:latest
  #   container_name: api_users
  #   ports:
  #     - "5000:5000"

volumes:
  upc_bibliotheque_data:
