apiVersion: v1
kind: ConfigMap
metadata:
  name: upc-config
data:
  DB_HOST: "upc-database-svc"
  DB_PORT: "3306"
  API_USER_HOST: "http://apiweb-svc:5000/api"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST_USER: "katumbachrist007@gmail.com"
  EMAIL_HOST_PASSWORD: "acdtmwzcczntclvn"
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq-svc/"
  CELERY_RESULT_BACKEND: "django-db"