apiVersion: v1
kind: Secret
metadata:
  name: upc-bibliotheque-database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Q2gxNmRvbmJvc2Nv
  MYSQL_DATABASE: YmlibGlvdGhlcXVl
  MYSQL_USER: ZGV2bWFzdGVy
  MYSQL_PASSWORD: Q2gxNmRvbmJvc2Nv